var data=[{
    // different species
    id:1001,
    name:"INFO",
    link1:"detailed.html?id=1001",
    link2:"detailed.html?id=1002",
    link3:"detailed.html?id=1003",
    link4:"detailed.html?id=1004",
    link5:"detailed.html?id=1005",
    link6:"detailed.html?id=1006",
    link7:"detailed.html?id=1007",
    link8:"detailed.html?id=1008",
    title:"Spotted Eagle Ray ",
    img:"asset/img/spotted_eagle_ray1.jpg",
    detail1:"Spotted eagle ray widths of nearly 11 feet (over 3 m), the spotted eagle ray is one of the largest eagle rays, with only the mantas growing bigger. Spotted eagle rays, like all eagle rays, are active swimmers and do not lie motionless on the seafloor, like the closely related whiptail stingrays (e.g., southern stingray). They are foraging predators and are known to eat a variety of invertebrate and fish prey. Just like the name implies, the spotted eagle ray is covered in spots and other markings. It is unmistakable with any other species throughout its range.Spotted eagle rays live along the open coast in warm waters throughout the world, though they are often associated with coral reefs and sometimes enter protected bays to feed or mate.",
    detail2:"They are generally considered a coastal species, but the worldwide geographic distribution implies that some individuals must migrate far distances over deep water. It is possible, however, that further genetic study will reveal that spotted eagle rays in different ocean basins (e.g., Atlantic vs. Pacific oceans) are actually different species.Spotted eagle rays reproduce via internal fertilization and give live birth. However, they do not connect to their young through a placenta, like in most mammals. Instead, embryos live off of energy obtained from yolk sacs, and only after the juveniles are able to survive on their own does the mother give birth to her young (1-4 pups per litter). This low reproductive potential, along with their natural rarity, contributes to experts considering spotted eagle rays as ‘near threatened, with extinction. This species is not directly targeted by commercial fisheries, but it is captured as accidental bycatch in fisheries targeting other species. Furthermore, it is occasionally captured alive to be displayed in public aquariums. Worldwide populations are declining, and careful monitoring is necessary to ensure that conservation measures can be enacted should populations reach threateningly low numbers."
},{
    id:1002,
    name:"INFO",
    link1:"detailed.html?id=1001",
    link2:"detailed.html?id=1002",
    link3:"detailed.html?id=1003",
    link4:"detailed.html?id=1004",
    link5:"detailed.html?id=1005",
    link6:"detailed.html?id=1006",
    link7:"detailed.html?id=1007",
    link8:"detailed.html?id=1008",
    title:"Whale Shark",
    img:"asset/img/whale_shark.jpg",
    detail1:"The largest fish in the world is the graceful, harmless whale shark. Though they reach the size of a school bus, whale sharks eat tiny plankton and fish eggs, which they filter feed as they swim slowly along with their giant mouths wide open. They are one of only three species of filter feeding sharks.Their incredible size may help them to survive long migrations to abundant food sources, between which they may not be able to find enough food. Scientists believe that some individuals swim across entire oceans to arrive just in time for a plankton bloom or a mass spawning of fish or coral eggs an amazing feat for a fish.As opposed to the other large sharks, which give birth to a small number of very large babies,",
    detail2:" whale sharks give birth to hundreds of very small babies (approximately 20 inches/45 cm). Even more interesting, after internal fertilization, the female whale shark actually produces hard, reinforced egg cases but then keeps them safely inside her abdomen until they hatch, at which point she gives live birth. The energy required to produce the unnecessary egg cases could perhaps be better utilized to produce more young, though it is possible that under some circumstances, the female deposits her eggs to hatch on their own.Whale sharks are also unique in that they are covered with white spots, and every individual apparently has its own spot pattern. In fact, whale shark researchers utilize specialized computer software, originally designed for star mapping, to identify individual whale sharks from photos of their spot patterns. Using this technology, researchers will be able to tell if individuals that are photographed by tourists in Mexico are later photographed by fishermen in Belize, for example.Like many large, slow moving animals, the whale shark has been fished quite heavily over the last several decades, and individuals are often accidentally caught in fishing gear that targets other species. Whale shark meat is eaten in some parts of the world, and the fins are valuable as well. Scientists currently believe whale sharks to be vulnerable to extinction. Fortunately, a large tourism industry has been developed for viewing whale sharks in the wild, and their value alive is higher than their value to fishers. For that reason and because they are such impressive animals, most places arou."
},{
    id:1003,
    name:"INFO",
    link1:"detailed.html?id=1001",
    link2:"detailed.html?id=1002",
    link3:"detailed.html?id=1003",
    link4:"detailed.html?id=1004",
    link5:"detailed.html?id=1005",
    link6:"detailed.html?id=1006",
    link7:"detailed.html?id=1007",
    link8:"detailed.html?id=1008",
    title:"Spiny Dog Fish",
    img:"asset/img/spiny_dogfish.jpg",
    detail1:"The spiny dogfish may go by many names, including piked dogfish, rock salmon and spiky dog, but only one truly represents this shark's unique defense strategy. Using sharp, venomous spines in the front of each dorsal fin, the spiny dogfish is a small but mighty predator that isn't afraid to take a jab at passing fish. They are considered one of the most abundant living shark species in the ocean, but are harmless to humans.Dogfish sharks make up the second largest order of sharks at 119 species. Sharks that are grouped into the dogfish family are so named because fishermen have observed these species chasing down smaller fish in dog-like packs.",
    detail2:"Schools of dogfish sharks numbering in the hundreds swim close together during the day, hunting herring, mackerel and capelin, as well as squid and jellyfish in some cases. Despite sharp spines, this dogfish consumes its meals by biting down on prey with sharp teeth and a strong jaw.Scientists believe that spiny dogfish eat less in the winter months when they swim in extreme depths of up to 2,900 feet below the surface. During spring, the sharks will return closer to the surface looking a little thinner, but will quickly move to warmer, coastal waters for summer feeding.With a slender body and pointed snout, the spiny dogfish is a compact shark species reaching a maximum of 39 inches in males and 49 inches in females. Their skin is grey to brown on top and becomes increasingly paler, or even white, on the belly with small white spots running down each side of the body. The spiny dogfish is a highly migratory species one individual tagged in Washington made a 5,000-mile journey to Japan. The spiny dogfish also breaks records when it comes to gestation. These sharks have the longest pregnancy of any vertebrate at 22 to 24 months, or two years! Eggs develop in the female, gaining nutrients from yolk sacs, and live young are born at 20 to 33 centimeters. Even at a young age, newborn spiny dogfish pups may hunt fish two or three times their size. Predators of the spiny dogfish include larger sharks, seals, orcas, cod and red hake. To defend itself, the spiny dogfish may inject venom into predators from the two spines near the dorsal fins. Humans are only at risk if they improperly handle these sharks.Based on evidence of over-exploitation in their range and bycatch fisheries, global population of spiny dogfish are considered vulnerable by the IUCN Red List. Global populations have declined by more than 30 percent over the last 75 years. In some parts of the world, this shark has been targeted for its meat and fins. In 2014, Oceana applauded steps taken by the Atlantic States Marine Fisheries Commission to prohibit the finning of spiny dogfish. Other fisheries take the spiny dogfish as unwanted bycatch before discarding them back to sea. "
},{
    id:1004,
    name:"INFO",
    link1:"detailed.html?id=1001",
    link2:"detailed.html?id=1002",
    link3:"detailed.html?id=1003",
    link4:"detailed.html?id=1004",
    link5:"detailed.html?id=1005",
    link6:"detailed.html?id=1006",
    link7:"detailed.html?id=1007",
    link8:"detailed.html?id=1008",
    title:"Shovel Guaiter Fish",
    img:"asset/img/shovel_guaiter_fish.webp",
    detail1:"The shovelnose guitarfish is a relatively small-bodied ray that has the typical wing-like pectoral fins of all rays but a body that otherwise resembles a shark's. Like most rays, this species lives on the seafloor, typically settled on soft sandy or muddy bottoms, often near rocky reefs. Shovelnose guitarfish have the ability to pump water over their gills, so they are able to remain perfectly motionless. The guitarfishes are a group of skates (as opposed to stingrays). They do not have barbs or “stingers” like some other rays, and they are totally harmless to people.As shovelnose guitarfish are associated with the seafloor, the majority of the prey also lives on the bottom.",
    detail2:"They eat a variety of benthic fishes and invertebrates, especially decapods like shrimps and crabs. Large, coastal sharks and perhaps California sea lions are the only known predators of shovelnose guitarfish.Like all sharks and rays, this species reproduces via internal fertilization. Each individual embryo receives nutrition from a yolk sac, and females give birth to live, well-developed young. After birth, juveniles receive no further parental care and are ready to begin living a predatory lifestyle. The shovelnose guitarfish has a shark-like body, and early scientists thought it was a shark. Later, it was thought to be intermediate between sharks and rays. Recent studies, however, have confirmed that the guitarfishes are rays and are most closely related to the diverse group of skates.Shovelnose guitarfish are directly targeted in small fisheries throughout much of their range. They are also accidentally captured in net fisheries targeting other species. In some areas (particularly in northern Mexico), their numbers have been depleted significantly, and scientists now believe that the species is near threatened with extinction. Continued monitoring of shovelnose guitarfish populations is important to ensure that any negative trends do not become too serious."
},{
    id:1005,
    name:"INFO",
    link1:"detailed.html?id=1001",
    link2:"detailed.html?id=1002",
    link3:"detailed.html?id=1003",
    link4:"detailed.html?id=1004",
    link5:"detailed.html?id=1005",
    link6:"detailed.html?id=1006",
    link7:"detailed.html?id=1007",
    link8:"detailed.html?id=1008",
    title:"Porcupine Ray",
    img:"asset/img/porcupine_ray.jpg",
    detail1:"A layer of sharp thorns on its back gives this ray a considerable edge over any predators looking for a bite. The spikes, which are a mixture of large, cone-shaped thorns and smaller, pointed scales known as denticles, are critical for the porcupine ray as they lack the venomous barb most stingray species use for warding off larger animals. The porcupine ray is a rarely seen and distinctive ray species that unfortunately faces many threats in its range.The porcupine ray is aptly named for its prickly body that acts as armor against a litany of predators.Stingray species are often vulnerable to the appetites of hammerhead and bull sharks, killer whales and other carnivorous fish.Stingray species are often vulnerable to the appetites of hammerhead and bull sharks, killer whales and other carnivorous fish.Stingray species are often vulnerable to the appetites of hammerhead and bull sharks, killer whales and other carnivorous fish.",
    detail2:"Though the porcupine ray has a signature whip-like tail similar to other stingrays, theirs does not hold venom for stunning predators. The porcupine ray's body is flattened into an oval-shaped disc with a rounded snout, and is usually shaded brown or grey above and white below. Its black tail stands out against its light body, and appears darker towards the tip. The porcupine ray inhabits the Indian Ocean and the Indo-West Pacific, concentrating around East Africa, the Red Sea and parts of Australia where tropical, inshore waters give way to coral reefs and sandy seafloors.The reproductive habits of porcupine rays have rarely been observed, but females most likely retain their eggs internally as most other stingrays do until the eggs are fully developed and then the female can give birth to a live litter. Newborn porcupine rays lack the species characteristic sharp thorns, but are still equipped with countless denticles on the upper part of the body. Porcupine rays forage for bottom-dwelling crustaceans, marine worms and fish that burrow into soft, sandy bottoms. Sharp rows of teeth in the ray's downward-facing jaws are ideal for breaking the hard, outer shells of its prey. Porcupine rays are benthic, which means they live near the sediment surface of the ocean. Benthic rays tend to “ripple” their fins to move around above the seafloor, in contrast to pelagic rays that flap their pectoral fins.Porcupine ray populations are declining today, and the species is considered vulnerable to extinction. Porcupine rays are not targeted by commercial fisheries, but they are often caught accidently by recreational fishermen in nearshore waters. Fewer porcupine rays are caught today as bycatch compared to years past, and researchers believe this means the species has been overexploited in its range and there are fewer individuals. Further, a porcupine ray's preferred habitat is in populated coastal areas that are more susceptible to human activity"
},{
    id:1006,
    name:"INFO",
    link1:"detailed.html?id=1001",
    link2:"detailed.html?id=1002",
    link3:"detailed.html?id=1003",
    link4:"detailed.html?id=1004",
    link5:"detailed.html?id=1005",
    link6:"detailed.html?id=1006",
    link7:"detailed.html?id=1007",
    link8:"detailed.html?id=1008",
    title:"Blue Ribbontail Ray",
    img:"asset/img/blue_spotted_ribbontail_ray.jpg",
    detail1:"Blue spotted ribbontail rays are named for the striking blue spots covering their body. They frequent the coral reefs and sandy flats in the Indo-Pacific Ocean, keeping close to the seafloor where they feed.These foragers dig in the sand, hunting shallow sand-dwelling animals like shrimp and crabs. Unlike most rays, blue spotted ribbontail rays will rarely bury themselves completely,2 though they sometimes will to ambush prey or when they migrate in large groups to shallow, sandy areas.This is a species that prefers to be left alone and are far more likely to swim away from a fight. The blue spots are meant to tell predators and other animals to stay away.This is a species that prefers to be left alone and are far more likely to swim away from a fight. The blue spots are meant to tell predators and other animals to stay away.This is a species that prefers to be left alone and are far more likely to swim away from a fight. The blue spots are meant to tell predators and other animals to stay away,",
    detail2:"If cornered they can lash out with the poisoned barb on the end of their tails, and that venom can prove fatal to many species, including humans.3Blue spotted ribbontail rays reproduce via eggs that grow inside the mother's body for a period of four months to a year, and live rays are born shortly after hatching inside the mother.4These rays are threatened around the world due to destructive fishing practices and habitat loss.1 They are also sometimes traded in the private aquarium trade, though these rays rarely thrive in captivity.cornered they can lash out with the poisoned barb on the end of their tails, and that venom can prove fatal to many species, including humans.3Blue spotted ribbontail rays reproduce via eggs that grow inside the mother's body for a period of four months to a year, and live rays are born shortly after hatching inside the mother.4These rays are threatened around the world due to destructive fishing practices and habitat loss.1 They are also sometimes traded in the private aquarium trade, though these rays rarely thrive in captivity"
},{
    id:1007,
    name:"INFO",
    link1:"detailed.html?id=1001",
    link2:"detailed.html?id=1002",
    link3:"detailed.html?id=1003",
    link4:"detailed.html?id=1004",
    link5:"detailed.html?id=1005",
    link6:"detailed.html?id=1006",
    link7:"detailed.html?id=1007",
    link8:"detailed.html?id=1008",
    title:"Pacific Angle Shark<",
    img:"asset/img/pacific_angle_shark.jpg",
    detail1:"Pacific angel sharks live on soft bottoms near rocky reefs and kelp forests. Their color patterns and flat bodies allow them to blend in very well with the seafloor, and they are able to pump water over their gills, allowing them to remain perfectly still. Pacific angel sharks are ambush predators that patiently wait for prey species  typically a variety of bony fishes and some small sharks  to swim a bit too close. At that point, they can be quite explosive, lunging at their prey and extending their powerful jaws to create enough suction to swallow their prey whole. Their camouflage also serves as a means to avoid predation, but some large, coastal predators are known to prey on this shark.",
    detail2:"This species reproduces via internal fertilization and gives birth to well developed young.Embryos receive their nutrition from a yolk sac, and newly born juveniles are self sufficient predators. They do not receive any further parental care. Pacific angel sharks are slow growing, relatively slow to mature, and do not reach reproductive age until they are approximately 13 years old.Pacific angel sharks are not generally considered dangerous, but they have been known to bite SCUBA divers when provoked. Their habit of remaining perfectly still makes them easy to touch, and divers sometimes grab them. The natural defense mechanism is to strike when threatened, but the bites are not generally severe. This shark is targeted directly and is captured in fisheries targeting other species. It is currently being overfished, and scientists consider it to be near threatened with extinction. Several other species of angelshark are worse off, considered either endangered (highly vulnerable to extinction) or critically endangered (very highly vulnerable to extinction). The group, in general, is now one of the most at risk groups of sharks on the planet. Without careful management of the human activities that affect these interesting, flat sharks, populations may continue to decline, perhaps to a species-threatening degree."
},{
    id:1008,
    name:"INFO",
    link1:"detailed.html?id=1001",
    link2:"detailed.html?id=1002",
    link3:"detailed.html?id=1003",
    link4:"detailed.html?id=1004",
    link5:"detailed.html?id=1005",
    link6:"detailed.html?id=1006",
    link7:"detailed.html?id=1007",
    link8:"detailed.html?id=1008",
    title:"Twin Wing Fly Fish",
    img:"asset/img/tropical_twin_wing_flyfish.jpg",
    detail1:"The tropical two-wing flyingfish gets its common name from the region where it lives (the tropics), the fact that it has greatly enlarged pectoral fins (“wings”), and its ability to glide long distances outside of the water to escape predation. It is one of approximately 65 species of flyingfishes, which do not actually fly and would perhaps be better called “glidingfishes” as they cannot change direction. The two-wing flyingfishes glide with their enlarged pectoral fins, while the four-wing flyingfishes also have enlarged pelvic fins that contribute to their gliding ability.Tropical two-wing flyingfish feed on plankton crustaceans and other small invertebrates.",
    detail2:"They have large eyes and excellent eyesight and can therefore hunt and eat individual plankton. This is in stark contrast to the very large-bodied filter feeders (like the whale shark or basking shark), which blindly filter huge volumes of water in order to obtain sufficient food. Tropical two-wing flyingfish are a favorite prey species of swordfish, common dolphinfish, tunas, billfishes, and other open ocean predators. In its attempt to avoid predation, this flyingfish can glide for long distances above the water surface. For a predator that spends its entire life in the water, the flyingfish’s ability to glide is akin to being able to disappear.Most flyingfishes live exclusively offshore, in the open ocean. Tropical two-wing flyingfish, however, occasionally also live closer to the coast and can be observed or captured inshore. Unlike some other species of flyingfishes that attach their eggs to floating objects, this species reproduces via broadcast spawning, where several females release their eggs and several males release their sperm into the surface water at the same time. This method increases the chance that eggs will become fertilized and decreases the likelihood that fertilized eggs will be eaten by egg predators.The tropical two-wing flyingfish is a common species with a large geographic range and is not targeted by large-scale, commercial fisheries. Though its conservation status has not been determined by scientists, it is almost certainly a species of least concern."
},{
    // fish
    id:"1009",
    name:"INFO",
    link1:"detailed.html?id=1009",
    link2:"detailed.html?id=1010",
    link3:"detailed.html?id=1011",
    link4:"detailed.html?id=1012",
    link5:"detailed.html?id=1013",
    link6:"detailed.html?id=1014",
    link7:"detailed.html?id=1015",
    link8:"detailed.html?id=1016",
    title:"Blue Tang",
    img:"asset/img/blue-tang.jpg",
    detail1:"True blue tangs are restricted to coral reefs in the Caribbean Sea and surrounding waters and are often confused with two other surgeonfishes that inhabit the same waters, the doctorfish and ocean surgeonfish, as all three species look similar. Furthermore, another surgeonfish that lives in the tropical Pacific Ocean (and was made famous as Dory in the Finding Nemo movies) is sometimes incorrectly called a blue tang. That species (Paracanthurus hepatus) is more properly known as the regal tang or powder blue tang, and it does not closely resemble the blue tang, visually.Blue tangs are herbivores, and they actively browse the surface of coral reefs, searching for their favorite algae.Blue tangs are herbivores, and they actively browse the surface of coral reefs, searching for their favorite algae. searching for their favorite algae. searching for their favorite algae.",
    detail2:"Though larger individuals sometimes browse by themselves or in pairs or threesomes, small to medium adults often form large groups and swim long distances, browsing along the reef surface throughout the day. With overfishing of their main predators (e.g., large groupers and snappers) and a reduction of some of their main competitors for algae (e.g., the Longspine Urchin), numbers of adult blue tangs can be quite high on many reefs. Juveniles live among dead coral rubble or in mangrove forests in more protected waters and move to the open reef surface as they mature. Adult blue tangs are solid blue (or almost dark purple), while juveniles are solid yellow.Blue tangs reproduce through a behavior known as broadcast spawning, where several females release eggs and several males release sperm into the water column above the reef, all at the same time. This method increases the likelihood that eggs will become successfully fertilized and that fertilized eggs will not be eaten by egg predators on the reef surface.Blue tangs are consumed by humans only rarely, when caught in artisanal fish traps, but bright yellow juveniles are targeted quite significantly in some locations for the private aquarium trade. Even so, scientists have assessed the blue tang's population status and have found it to be a species of least concern (i.e., its numbers are currently fine"
},{
    id:"1010",
    name:"INFO",
    link1:"detailed.html?id=1009",
    link2:"detailed.html?id=1010",
    link3:"detailed.html?id=1011",
    link4:"detailed.html?id=1012",
    link5:"detailed.html?id=1013",
    link6:"detailed.html?id=1014",
    link7:"detailed.html?id=1015",
    link8:"detailed.html?id=1016",
    title:"Blue Merlin",
    img:"asset/img/blue_merlin.jpg",
    detail1:"This species is known for its long bill that grows from the front of its head. Blue marlin use this bill to stun their prey by slashing their heads in a side-to-side motion, knocking potential prey unconscious, and making it easier to catch. The blue marlin's bill differs from the swordfish's and the sailfish's by being round and pointed, rather than flat and blunt. Like many open ocean bony fishes, blue marlin start out as extremely tiny larvae, no more than a few millimeters long and weighing only a few hundredths of a gram. Soon after hatching, they already have a visible bill. Blue marlin grow rapidly, and in the course of their lives they may increase their body weight by at least one million times.This species is known for its long bill that grows from the front of its head. Blue marlin use this bill to stun their prey by slashing their heads in a side-to-side motion, knocking potential prey unconscious, and making it easier to catch. The blue marlin's bill differs from the swordfish's and the sailfish's by being round and pointed, rather than flat and blunt. Like many open ocean bony fishes, blue marlin start out as extremely tiny larvae, no more than a few millimeters long and weighing only a few hundredths of a gram. Soon after hatching, they already have a visible bill. Blue marlin grow rapidly, and in the course of their lives they may increase their body weight by at least one million times. and in the course of their lives they may increase their body weight by at least one million times. and in the course of their lives they may increase their body weight by at least one million times.",
    detail2:"Because blue marlin undergo such an amazing transformation in size(from being nearly microscopic to being one of the largest open ocean predators), they eat a wide variety of prey, throughout their lifetimes. At a young age, they eat tiny zooplankton, and their prey increases in size as they do. As adults, they eat fairly large bony fishes and squids. Similarly, blue marlin are eaten by a wide variety of predators. When they are newly hatched, they are eaten by other fishes that specialize on eating plankton. The size of their predators increases as they grow, and adult blue marlin are not eaten by anything other than large open ocean shark species.The blue marlin is a highly migratory species, with individuals migrating across entire ocean basins and even between oceans. One individual, for example, was tagged off the east coast of the United States (western Atlantic Ocean) and recaptured in the Indian Ocean. Like many migratory species, the females are larger than males. In fact, adult female blue marlin are as much as four times the size of the largest males. All of the largest individuals are female.  blue marlin reproduce through external (rather than internal) fertilization, where the female releases her eggs into the water column while the male releases his sperm. Once the sperm find the eggs, fertilization occurs.  While spawning, a single female may release several million eggs, increasing the likelihood that some will be fertilized and that at least one hatched larva will grow to reach adulthood. Though almost all fishes are cold blooded, blue marlin and the other billfishes have a specialized blood vessel structure called a countercurrent exchanger  that allows them to warm their brains and eyes. This adaptation provides them with a major advantage when hunting, by allowing them to think more quickly and see more clearly.The blue marlin is a targeted fishery species in only a limited number of areas but is captured as accidental bycatch in fisheries targeting other species throughout its range. In some areas, this accidental capture is threatening blue marlin populations, and scientists consider the species vulnerable to extinction. Generally speaking, blue marlin populations are decreasing in numbers. Though it is not targeted commercially throughout much of its range, the blue marlin is one of the most highly sought after big game fishes in the world. Sport fishing enthusiasts spend tens of thousands of dollars to catch large blue marlin, and they are typically released alive (though recent data suggests that released individuals may frequently die after the fact).  If numbers continue to decline, this highly valuable sport fishery may be in danger of collapse."
},{
    id:"1011",
    name:"INFO",
    link1:"detailed.html?id=1009",
    link2:"detailed.html?id=1010",
    link3:"detailed.html?id=1011",
    link4:"detailed.html?id=1012",
    link5:"detailed.html?id=1013",
    link6:"detailed.html?id=1014",
    link7:"detailed.html?id=1015",
    link8:"detailed.html?id=1016",
    title:"Common Clown Fish",
    img:"asset/img/common_clownfish.jpg",
    detail1:"Though they spend much of their lives swimming among the tentacles of their host anemone, common clownfish occasionally leave to feed. They are plankton pickers, which means they visually seek and eat individual zooplankton or phytoplankton floating in the water column. They also likely eat algae from the reef surface. Because of the protection afforded them by their host anemones, common clownfish have few predators,the protection afforded them by their host anemones, common clownfish have few predators,",
    detail2:" but they are at risk of predation when they leave the anemone to feed.The common clownfish's lifecycle is both interesting and rare.Like all clownfishes, this species changes sex throughout its lifetime. Sex change is not particularly rare, but most species change from female to male. The clownfishes change from male to female. All individuals hatch as males and eventually join groups of a few individuals living together in an anemone. The largest individual of each group is the only female, and she and the largest male are the only two that reproduce. The large, dominant female lays her eggs on the reef surface, and the male fertilizes them. Together, they guard the nest from egg predators until they hatch. If anything happens to the female, the reproductive male changes sex, becoming the dominant female.The next largest male then becomes reproductively active, and the other males in the group continue to be subordinate.The common clownfish is extremely popular in the aquarium trade. Some individuals are bright orange and white, while others are dark black and white. The stark colors and the relationship with anemones make this species highly desirable for public and private aquaria. They have long been collected for sale in that industry, but recent efforts to promote reproduction in captivity have been successful, so many of the individuals for sale in pet stores have been reared in aquaria. The conservation status of this species is currently unknown, but it has likely been depleted in some areas as a result of its collection for the pet trade. Fortunately, the continued development of a captive breeding program has reduced the pressure on wild populations."
},{
    id:"1012",
    name:"INFO",
    link1:"detailed.html?id=1009",
    link2:"detailed.html?id=1010",
    link3:"detailed.html?id=1011",
    link4:"detailed.html?id=1012",
    link5:"detailed.html?id=1013",
    link6:"detailed.html?id=1014",
    link7:"detailed.html?id=1015",
    link8:"detailed.html?id=1016",
    title:"Mexican Look Down",
    img:"asset/img/mexican_lookdown.jpg",
    detail1:"The Mexico lookdown is native to shallow, coastal waters from the Baja California Peninsula, Mexico to northern South America. Mexican lookdowns are foraging predators that feed over sandy and muddy soft bottoms. They are known to eat a variety of small invertebrates  including shrimps, squids, and polychaete worms  as well as small fishes. They feed in small schools but do not have coordinated hunting/foraging behavior. Though Mexican lookdowns are eaten by large, coastal fishes and sharks, they have little nutritional value because they are so incredibly thin. They are excellent swimmers and can often outmaneuver potential predators. They are known to eat a variety of small invertebrates  including shrimps, squids, and polychaete worms  as well as small fishes. They feed in small schools but do not have coordinated hunting/foraging behavior. Though Mexican lookdowns are eaten by large, coastal fishes and sharks, they have little nutritional value because they are so incredibly thin. They are excellent swimmers and can often outmaneuver potential predators.",
    detail2:"This species reproduces through a behavior known as broadcast spawning, where females release eggs and males release sperm into the water column, above the seafloor, at the same time.This method increases the likelihood that eggs will become successfully fertilized and that fertilized eggs will not be eaten by egg predators near the bottom.The Mexican lookdown is fished for local consumption throughout its range, but it has little commercial value. It is also accidentally captured in net fisheries targeting other species and targeted in catch-and-release sport fisheries, but none of these fishing activities is currently threatening this species. Though population trends are not well known, they are assumed to be stable, and the Mexican lookdown is a species of least conservation concern."
},{
    id:"1013",
    name:"INFO",
    link1:"detailed.html?id=1009",
    link2:"detailed.html?id=1010",
    link3:"detailed.html?id=1011",
    link4:"detailed.html?id=1012",
    link5:"detailed.html?id=1013",
    link6:"detailed.html?id=1014",
    link7:"detailed.html?id=1015",
    link8:"detailed.html?id=1016",
    title:"Yellow Fin Tuna",
    img:"asset/img/yellow_fin_tuna.jpg",
    detail1:"The yellowfin tuna is one of the open ocean's fastest, strongest predators and an important fishery species everywhere that it lives. Reaching weights of at least 400 pounds (~190 kg) and lengths of nearly 7 feet (~2 m), the yellowfin tuna is a large species that will eat just about anything that it can swallow (typically whole). Like many open ocean bony fishes, yellowfin tunas start out as extremely tiny larvae, no more than a few millimeters long and weighing only a few hundredths of a gram. Within two years, individuals reach lengths of 3 feet (~ one meter) and are sexually mature.Because yellowfin tunas undergo Within two years, individuals reach lengths of 3 feet (~ one meter) and are sexually mature.Because yellowfin tunas undergo Within two years, individuals reach lengths of 3 feet (~ one meter) and are sexually mature.Because yellowfin tunas ",
    detail2:"such an amazing transformation in size (from being nearly microscopic to being one of the largest open ocean predators), they eat a wide variety of prey, throughout their lifetimes. At a young age, they eat tiny zooplankton, and their prey increases in size as they do. As adults, they eat fairly large bony fishes and squids. Similarly, yellowfin tunas are eaten by a wide variety of predators. When they are newly hatched, they are eaten by other fishes that specialize on eating plankton. At that life stage, their numbers are reduced dramatically. Those that survive face a steady increase in the size of their predators. Adult yellowfins are not eaten by anything other than the very largest billfishes, toothed whales, and some open ocean shark species.Yellowfin tunas are known to be highly migratory, with individuals making long migrations every year. These migrations likely correspond with their spawning behavior and with their food needs. This species reproduces via broadcast spawning, where several females and several males release millions of eggs and sperm into the water column at the same time. This method increases the likelihood that the eggs will be fertilized and decreases the chances that they will be eaten by egg predators. Though almost all fishes are cold blooded, yellowfin tunas have a specialized blood vessel structure called a countercurrent exchanger that allows them to maintain a body temperature that is higher than the surrounding water. This adaptation provides them with a major advantage when hunting in cold water, by allowing them to move more quickly and intelligently. The yellowfin tuna is one of the fastest swimmers in the ocean. Like some shark species, yellowfin tunas must constantly swim.  In order to obtain oxygen from the water, fishes pass water over their gills. The tunas lack the ability to do so while stopped, so they must continuously swim forward with their mouths open to keep their blood oxygenated.The yellowfin tuna is a highly prized food fish and is fished heavily throughout its range. Generally, scientists believe that these fisheries are managed fairly well, and the species is not considered overfished. However, there are some populations that are fished more heavily than others, and it is important to continue to monitor these activities in order to prevent fishing levels that could threaten this iconic, powerful species. In the 1980s, fisheries that targeted the yellowfin tuna were responsible for accidentally catching and killing several million spotted and spinner dolphins and sparked the famous and successful dolphin-safe tuna campaign. The tendency of adult yellowfin tunas to school with similarly sized adult dolphins led to the unfortunate habit of fishermen setting their nets on dolphin pods with the hope of catching the nearby tuna. That activity is now illegal in most places around the world."
},{
    id:"1014",
    name:"INFO",
    link1:"detailed.html?id=1009",
    link2:"detailed.html?id=1010",
    link3:"detailed.html?id=1011",
    link4:"detailed.html?id=1012",
    link5:"detailed.html?id=1013",
    link6:"detailed.html?id=1014",
    link7:"detailed.html?id=1015",
    link8:"detailed.html?id=1016",
    title:"Twin Wing Fly Fish",
    img:"asset/img/tropical_twin_wing_flyfish.jpg",
    detail1:"The tropical two-wing flyingfish gets its common name from the region where it lives (the tropics), the fact that it has greatly enlarged pectoral fins (“wings”), and its ability to glide long distances outside of the water to escape predation. It is one of approximately 65 species of flyingfishes, which do not actually fly and would perhaps be better called “glidingfishes” as they cannot change direction. The two-wing flyingfishes glide with their enlarged pectoral fins, while the four-wing flyingfishes also have enlarged pelvic fins that contribute to their gliding ability.Tropical two-wing flyingfish feed on plankton crustaceans and other small invertebrates.Tropical two-wing flyingfish feed on plankton crustaceans and other small invertebrates.Tropical two-wing flyingfish feed on plankton crustaceans and other small invertebrates.",
    detail2:"They have large eyes and excellent eyesight and can therefore hunt and eat individual plankton. This is in stark contrast to the very large-bodied filter feeders (like the whale shark or basking shark), which blindly filter huge volumes of water in order to obtain sufficient food. Tropical two-wing flyingfish are a favorite prey species of swordfish, common dolphinfish, tunas, billfishes, and other open ocean predators. In its attempt to avoid predation, this flyingfish can glide for long distances above the water surface. For a predator that spends its entire life in the water, the flyingfish's ability to glide is akin to being able to disappear.Most flyingfishes live exclusively offshore, in the open ocean. Tropical two-wing flyingfish, however, occasionally also live closer to the coast and can be observed or captured inshore. Unlike some other species of flyingfishes that attach their eggs to floating objects, this species reproduces via broadcast spawning, where several females release their eggs and several males release their sperm into the surface water at the same time. This method increases the chance that eggs will become fertilized and decreases the likelihood that fertilized eggs will be eaten by egg predators.The tropical two-wing flyingfish is a common species with a large geographic range and is not targeted by large-scale, commercial fisheries. Though its conservation status has not been determined by scientists, it is almost certainly a species of least concern."
},{
    id:"1015",
    name:"INFO",
    link1:"detailed.html?id=1009",
    link2:"detailed.html?id=1010",
    link3:"detailed.html?id=1011",
    link4:"detailed.html?id=1012",
    link5:"detailed.html?id=1013",
    link6:"detailed.html?id=1014",
    link7:"detailed.html?id=1015",
    link8:"detailed.html?id=1016",
    title:"Banded Butterfly Fish",
    img:"asset/img/banded-butterflyfish.jpg",
    detail1:"The Banded butterflyfish is a small-bodied fish that lives on coral reefs of the western Atlantic Ocean. Like all butterflyfishes, the Banded butterflyfish has a discus body and a very small mouth, perfect for biting its preferred prey  small worms and live, soft tissue of reef-building corals. This species gets its common name from the series of dark, vertical bars (or bands) that help to provide it with camouflage. One of the bands always covers the eye, hiding it from potential predators and preventing predators from being able to easily determine which end of the body is the head and which end is the tail.Though generally considered to be foraging predators, which lazily search the reef surface for food, One of the bands always covers the eye, hiding it from potential predators and preventing predators from being able to easily determine which end of the body is the head and which end is the tail.Though generally considered to be foraging predators, which lazily search the reef surface for food, which lazily search the reef surface for food,",
    detail2:"Banded butterflyfish actually utilize a variety of feeding strategies. Some (often in pairs) do forage on the reef surface. Others form larger schools that visually hunt tiny plankton in the water column above the reef. Still others are known to engage in cleaning behavior, where a larger fish (potentially of a species known to eat Banded butterflyfish) approaches a group of this species in order to be cleaned of parasites. The intricate behaviors that signal that the predator is approaching to be cleaned rather than to attack are not fully understood by fish researchers.Banded butterflyfish reproduce through a behavior known as broadcast spawning, where a female releases her eggs and a male releases sperm into the water column above the reef, at the same time. This method increases the likelihood that fertilized eggs will not be eaten by egg predators on the reef surface and will instead be carried away by the currents. Unlike in several other species of reef fishes, however, the Banded butterflyfish does not reproduce in groups and instead forms monogamous pairs before this spawning behavior.The Banded butterflyfish is generally restricted to the Caribbean basin and surrounding waters (Gulf of Mexico, Florida, Bermuda), but individuals are occasionally observed along the coast of New England and even in European waters. In those cases, scientists believe that the observed individuals were carried by strong, warm currents during particularly warm years. Scientists do not believe that they are able to reproduce and form viable, permanent populations in these regions. This species is not eaten by people, but it is captured for display in public and private aquaria. Currently, scientists do not believe that the species is at any risk of extinction, and population sizes are apparently stable. However, it is important to continue to monitor Banded butterflyfish populations in order to ensure that any changes resulting from capture of adults or from expected negative trends in coral reef health throughout its range will be identified at an early stage"
},{
    id:"1016",
    name:"INFO",
    link1:"detailed.html?id=1009",
    link2:"detailed.html?id=1010",
    link3:"detailed.html?id=1011",
    link4:"detailed.html?id=1012",
    link5:"detailed.html?id=1013",
    link6:"detailed.html?id=1014",
    link7:"detailed.html?id=1015",
    link8:"detailed.html?id=1016",
    title:"Blue Head Wrasse",
    img:"asset/img/bluehead-wrasse.jpg",
    detail1:"It gets its common name from the adult coloration, which includes an obviously blue head on an otherwise green body. Juveniles are solid yellow, or nearly so, with a black spot on the dorsal fin. The numerical success of the bluehead wrasse is apparent to anyone who has visited a Caribbean reef; it is one of the most common species in that region.Bluehead wrasses are generalist foragers and eat a variety of prey.They are known to forage for small invertebrates and crustaceans on the reef surface, target individual zooplankton in the water above the reef surface, and clean the parasites off of larger species. As they are one of the most common small-bodied fishes on reefs,It gets its common name from the adult coloration, which includes an obviously blue head on an otherwise green body. Juveniles are solid yellow, or nearly so, with a black spot on the dorsal fin. The numerical success of the bluehead wrasse is apparent to anyone who has visited a Caribbean reef; it is one of the most common species in that region.Bluehead wrasses are generalist foragers and eat a variety of prey.They are known to forage for small invertebrates and crustaceans on the reef surface, target individual zooplankton in the water above the reef surface, and clean the parasites off of larger species. As they are one of the most common small-bodied fishes on reefs,",
    detail2:" bluehead wrasses are eaten by many different species of predatory fishes. The bluehead wrasse's complex mating system has been a topic of scientific study for decades.This species reproduces through a behavior known as broadcast spawning, where females release eggs and males release sperm into the water column above the reef, at the same time. This method increases the likelihood that eggs will become successfully fertilized and that fertilized eggs will not be eaten by egg predators on the reef surface. All bluehead wrasses hatch as females. As they mature, some individuals become male. Young (though mature) males continue to resemble females in appearance and participate in group spawning with large groups of females and other males. As they continue to mature, the largest males transition into the so-called terminal males, when they finally develop the blue head and green body. These largest males defend territories and develop harems of females with which they spawn one at a time. Spawning still requires the broadcast method described above, but the terminal males prevent (via aggressive behavior) other males from participating. As a result of these transitions, bluehead wrasses may reproduce in four different ways throughout their lifetime: 1) as a female in a group spawning event; 2) as a female in a pair spawning event within the territory of a large male; 3) as a small male in a group spawning event; and 4) as a dominant, terminal male in a pair spawning event within its own territory. Interestingly, small males release more sperm than large dominant males because their sperm must compete with that of other males, while a dominant male competes with other males before (rather than during) spawning.The bluehead wrasse is too small to be eaten but is captured for display in public and private aquaria. Currently, scientists do not believe that the species is at any risk of extinction, and population sizes are apparently stable. However, it is important to continue to monitor bluehead wrasse populations in order to ensure that any changes resulting from capture of adults or from expected negative trends in coral reef health throughout its range will be identified at an early stage."
},{
    // atlantic 
    id:"1017",
    name:"INFO",
    link1:"detailed.html?id=1017",
    link2:"detailed.html?id=1018",
    link3:"detailed.html?id=1019",
    link4:"detailed.html?id=1020",
    link5:"detailed.html?id=1021",
    link6:"detailed.html?id=1022",
    link7:"detailed.html?id=1023",
    link8:"detailed.html?id=1024",
    title:"Atlantic Blue Tuna",
    img:"asset/img/atlantic_blue_tuna.jpg",
    detail1:"",
    detail2:""

},{
    id:"1018",
    name:"INFO",
    link1:"detailed.html?id=1017",
    link2:"detailed.html?id=1018",
    link3:"detailed.html?id=1019",
    link4:"detailed.html?id=1020",
    link5:"detailed.html?id=1021",
    link6:"detailed.html?id=1022",
    link7:"detailed.html?id=1023",
    link8:"detailed.html?id=1024",
    title:"Atlantic Cod",
    img:"asset/img/atlantic_cod.jpg",
    detail1:"",
    detail2:""

},{
    id:"1019",
    name:"INFO",
    link1:"detailed.html?id=1017",
    link2:"detailed.html?id=1018",
    link3:"detailed.html?id=1019",
    link4:"detailed.html?id=1020",
    link5:"detailed.html?id=1021",
    link6:"detailed.html?id=1022",
    link7:"detailed.html?id=1023",
    link8:"detailed.html?id=1024",
    title:"Atlantic Salmon",
    img:"asset/img/atlantic_salmon.jpg",
    detail1:"",
    detail2:""

},{
    id:"1020",
    name:"INFO",
    link1:"detailed.html?id=1017",
    link2:"detailed.html?id=1018",
    link3:"detailed.html?id=1019",
    link4:"detailed.html?id=1020",
    link5:"detailed.html?id=1021",
    link6:"detailed.html?id=1022",
    link7:"detailed.html?id=1023",
    link8:"detailed.html?id=1024",
    title:"Atlantic Trumpet Fish",
    img:"asset/img/atlantic_trumpetfish.jpg",
    detail1:"",
    detail2:""

},{
    id:"1021",
    name:"INFO",
    link1:"detailed.html?id=1017",
    link2:"detailed.html?id=1018",
    link3:"detailed.html?id=1019",
    link4:"detailed.html?id=1020",
    link5:"detailed.html?id=1021",
    link6:"detailed.html?id=1022",
    link7:"detailed.html?id=1023",
    link8:"detailed.html?id=1024",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1022",
    name:"INFO",
    link1:"detailed.html?id=1017",
    link2:"detailed.html?id=1018",
    link3:"detailed.html?id=1019",
    link4:"detailed.html?id=1020",
    link5:"detailed.html?id=1021",
    link6:"detailed.html?id=1022",
    link7:"detailed.html?id=1023",
    link8:"detailed.html?id=1024",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1023",
    name:"INFO",
    link1:"detailed.html?id=1017",
    link2:"detailed.html?id=1018",
    link3:"detailed.html?id=1019",
    link4:"detailed.html?id=1020",
    link5:"detailed.html?id=1021",
    link6:"detailed.html?id=1022",
    link7:"detailed.html?id=1023",
    link8:"detailed.html?id=1024",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1024",
    name:"INFo",
    link1:"detailed.html?id=1017",
    link2:"detailed.html?id=1018",
    link3:"detailed.html?id=1019",
    link4:"detailed.html?id=1020",
    link5:"detailed.html?id=1021",
    link6:"detailed.html?id=1022",
    link7:"detailed.html?id=1023",
    link8:"detailed.html?id=1024",
    title:"",
    detail1:"",
    detail2:""

},{
    // shark
    id:"1025",
    name:"INFo",
    link1:"detailed.html?id=1025",
    link2:"detailed.html?id=1026",
    link3:"detailed.html?id=1027",
    link4:"detailed.html?id=1028",
    link5:"detailed.html?id=1029",
    link6:"detailed.html?id=1030",
    link7:"detailed.html?id=1031",
    link8:"detailed.html?id=1032",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1026",
    name:"INFo",
    link1:"detailed.html?id=1025",
    link2:"detailed.html?id=1026",
    link3:"detailed.html?id=1027",
    link4:"detailed.html?id=1028",
    link5:"detailed.html?id=1029",
    link6:"detailed.html?id=1030",
    link7:"detailed.html?id=1031",
    link8:"detailed.html?id=1032",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1027",
    name:"INFo",
    link1:"detailed.html?id=1025",
    link2:"detailed.html?id=1026",
    link3:"detailed.html?id=1027",
    link4:"detailed.html?id=1028",
    link5:"detailed.html?id=1029",
    link6:"detailed.html?id=1030",
    link7:"detailed.html?id=1031",
    link8:"detailed.html?id=1032",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1028",
    name:"INFo",
    link1:"detailed.html?id=1025",
    link2:"detailed.html?id=1026",
    link3:"detailed.html?id=1027",
    link4:"detailed.html?id=1028",
    link5:"detailed.html?id=1029",
    link6:"detailed.html?id=1030",
    link7:"detailed.html?id=1031",
    link8:"detailed.html?id=1032",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1029",
    name:"INFo",
    link1:"detailed.html?id=1025",
    link2:"detailed.html?id=1026",
    link3:"detailed.html?id=1027",
    link4:"detailed.html?id=1028",
    link5:"detailed.html?id=1029",
    link6:"detailed.html?id=1030",
    link7:"detailed.html?id=1031",
    link8:"detailed.html?id=1032",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1030",
    name:"INFo",
    link1:"detailed.html?id=1025",
    link2:"detailed.html?id=1026",
    link3:"detailed.html?id=1027",
    link4:"detailed.html?id=1028",
    link5:"detailed.html?id=1029",
    link6:"detailed.html?id=1030",
    link7:"detailed.html?id=1031",
    link8:"detailed.html?id=1032",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1031",
    name:"INFo",
    link1:"detailed.html?id=1025",
    link2:"detailed.html?id=1026",
    link3:"detailed.html?id=1027",
    link4:"detailed.html?id=1028",
    link5:"detailed.html?id=1029",
    link6:"detailed.html?id=1030",
    link7:"detailed.html?id=1031",
    link8:"detailed.html?id=1032",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1032",
    name:"INFo",
    link1:"detailed.html?id=1025",
    link2:"detailed.html?id=1026",
    link3:"detailed.html?id=1027",
    link4:"detailed.html?id=1028",
    link5:"detailed.html?id=1029",
    link6:"detailed.html?id=1030",
    link7:"detailed.html?id=1031",
    link8:"detailed.html?id=1032",
    title:"",
    detail1:"",
    detail2:""

},{
    // dolphin
    id:"1033",
    name:"INFo",
    link1:"detailed.html?id=1033",
    link2:"detailed.html?id=1034",
    link3:"detailed.html?id=1035",
    link4:"detailed.html?id=1036",
    link5:"detailed.html?id=1037",
    link6:"detailed.html?id=1038",
    link7:"detailed.html?id=1039",
    link8:"detailed.html?id=1040",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1034",
    name:"INFo",
    link1:"detailed.html?id=1033",
    link2:"detailed.html?id=1034",
    link3:"detailed.html?id=1035",
    link4:"detailed.html?id=1036",
    link5:"detailed.html?id=1037",
    link6:"detailed.html?id=1038",
    link7:"detailed.html?id=1039",
    link8:"detailed.html?id=1040",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1035",
    name:"INFo",
    link1:"detailed.html?id=1033",
    link2:"detailed.html?id=1034",
    link3:"detailed.html?id=1035",
    link4:"detailed.html?id=1036",
    link5:"detailed.html?id=1037",
    link6:"detailed.html?id=1038",
    link7:"detailed.html?id=1039",
    link8:"detailed.html?id=1040",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1036",
    name:"INFo",
    link1:"detailed.html?id=1033",
    link2:"detailed.html?id=1034",
    link3:"detailed.html?id=1035",
    link4:"detailed.html?id=1036",
    link5:"detailed.html?id=1037",
    link6:"detailed.html?id=1038",
    link7:"detailed.html?id=1039",
    link8:"detailed.html?id=1040",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1037",
    name:"INFo",
    link1:"detailed.html?id=1033",
    link2:"detailed.html?id=1034",
    link3:"detailed.html?id=1035",
    link4:"detailed.html?id=1036",
    link5:"detailed.html?id=1037",
    link6:"detailed.html?id=1038",
    link7:"detailed.html?id=1039",
    link8:"detailed.html?id=1040",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1038",
    name:"INFo",
    link1:"detailed.html?id=1033",
    link2:"detailed.html?id=1034",
    link3:"detailed.html?id=1035",
    link4:"detailed.html?id=1036",
    link5:"detailed.html?id=1037",
    link6:"detailed.html?id=1038",
    link7:"detailed.html?id=1039",
    link8:"detailed.html?id=1040",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1039",
    name:"INFo",
    link1:"detailed.html?id=1033",
    link2:"detailed.html?id=1034",
    link3:"detailed.html?id=1035",
    link4:"detailed.html?id=1036",
    link5:"detailed.html?id=1037",
    link6:"detailed.html?id=1038",
    link7:"detailed.html?id=1039",
    link8:"detailed.html?id=1040",
    title:"",
    detail1:"",
    detail2:""

},{
    id:"1040",
    name:"INFo",
    link1:"detailed.html?id=1033",
    link2:"detailed.html?id=1034",
    link3:"detailed.html?id=1035",
    link4:"detailed.html?id=1036",
    link5:"detailed.html?id=1037",
    link6:"detailed.html?id=1038",
    link7:"detailed.html?id=1039",
    link8:"detailed.html?id=1040",
    title:"",
    detail1:"",
    detail2:""

}]